export { default as HomeHero } from './hero'
export { default as industries } from './industries'
export { default as HomeFeature } from './feature'
export { default as HomeTestimonial } from './testimonial'
export { default as HomeOurMentors } from './leaders'
export { default as HomeNewsLetter } from './newsletter'
export { default as HomeOurBusiness } from './ourbusiness'
